title: Himanshu Garg
logo: /assets/img/Himanshu_Photo.png
description:
  <br>
  Data Scientist with experience of 6+ years, 
  having good understanding of Statistical and 
  Machine Learning techniques. Aspiring to 
  utilize my strong prioritization skills 
  and analytical ability to charter mutually 
  beneficial growth.
  <br>

theme: jekyll-theme-minimal
